name: Code quality

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      -main

jobs:
  lint-test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
