# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Carthage
      run: brew install carthage

    - name: Bootstrap Carthage
      run: carthage bootstrap --platform iOS
    
    - name: Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build
      run: xcodebuild build -project SwiftVN.xcodeproj -scheme SwiftVN clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No
      
    - name: Run tests
      run: xcodebuild test -project SwiftVN.xcodeproj -scheme SwiftVN clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=17.0,name=iPhone 13" CODE_SIGNING_ALLOWED=No
