# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Carthage
      run: brew install carthage

    - name: Bootstrap Carthage
      run: carthage bootstrap --platform iOS
    
    - name: Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Get commit SHA
      id: commitinfo
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Build
      run: xcodebuild build -project SwiftVN.xcodeproj -scheme SwiftVN clean build -configuration Release archive -archivePath build/SwiftVN.xcarchive -sdk iphoneos CODE_SIGNING_ALLOWED=No CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=No

    #- name: Run tests
    #  run: xcodebuild test -project SwiftVN.xcodeproj -scheme SwiftVN clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=18.0,name=iPhone 15" CODE_SIGNING_ALLOWED=No

    - name: Package ipa
      run: |
        mkdir payload
        cp -r build/SwiftVN.xcarchive/Products/Applications/SwiftVN.app payload
        zip -r SwiftVN-${{ steps.commitinfo.outputs.sha_short }}.ipa payload
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SwiftVN${{ steps.commitinfo.outputs.sha_short }}.ipa
        path: SwiftVN-${{ steps.commitinfo.outputs.sha_short }}.ipa
        if-no-files-found: error
      
    
